app/main/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint

from . import api_views

main = Blueprint('main', __name__)

main.add_url_rule('/', 'index', api_views.index)

main.add_url_rule('/api/notifications/creation/', view_func=api_views.UserNotificationListView.as_view('create_notification'))
main.add_url_rule('/api/notifications/sent/', view_func=api_views.UserNotificationListView.as_view('send_notifications'))
main.add_url_rule('/api/notifications/received/', view_func=api_views.UserNotificationListView.as_view('received_notifications'), defaults={'is_sent':False})
main.add_url_rule('/api/notifications/sent/<pk>/', view_func=api_views.UserNotificationDetailView.as_view('send_notification'))
main.add_url_rule('/api/notifications/received/<pk>/', view_func=api_views.UserNotificationDetailView.as_view('received_notification'), defaults={'is_sent':False})
main.add_url_rule('/api/notifications/draft/', view_func=api_views.NotificationDraftListModifyDeleteView.as_view('notification_drafts'))
main.add_url_rule('/api/notifications/draft/<pk>/', view_func=api_views.NotificationDraftListModifyDeleteView.as_view('notification_draft'))

app/accounts/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import datetime
from flask import render_template, redirect, request, flash, url_for, current_app, session, Blueprint
from flask.views import MethodView
from flask_login import login_user, logout_user, login_required, current_user
from flask_principal import Identity, AnonymousIdentity, identity_changed

from . import models, forms


accounts = Blueprint('accounts', __name__)

def get_current_user():
    try:
        return models.User.objects.get(username=current_user.username)
    except models.User.DoesNotExist:
        return None

def login():
    form = forms.LoginForm()
    if form.validate_on_submit():
        try:
            user = models.User.objects.get(username=form.username.data)
        except models.User.DoesNotExist:
            user = None

        if user and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            user.last_login = datetime.datetime.now
            user.save()
            identity_changed.send(current_app._get_current_object(), identity=Identity(user.username))
            return redirect(request.args.get('next') or url_for('main.index'))

        flash('Invalid username or password', 'danger')

    return render_template('accounts/login.html', form=form)

@login_required
def logout():
    logout_user()
    # Remove session keys set by Flask-Principal
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)

    # Tell Flask-Principal the user is anonymous
    identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())

    flash('You have been logged out', 'success')
    return redirect(url_for('accounts.login'))

def register(create_su=False):        
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        user = models.User()
        user.username = form.username.data
        user.password = form.password.data
        user.email = form.email.data

        user.display_name = user.username
        
        if create_su:
            user.is_superuser = True
        user.save()

        return redirect(url_for('main.index'))

    return render_template('accounts/registration.html', form=form)

@login_required
def add_user():
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        user = models.User()
        user.username = form.username.data
        user.password = form.password.data
        user.email = form.email.data

        user.display_name = user.username

        user.save()

        return redirect(url_for('accounts.users'))

    return render_template('accounts/registration.html', form=form)

def get_current_user():
    user = models.User.objects.get(username=current_user.username)
    return user


class Users(MethodView):
    decorators = [login_required]
    template_name = 'accounts/users.html'
    def get(self):
        users = models.User.objects.all()
        return render_template(self.template_name, users=users)

class User(MethodView):
    decorators = [login_required]
    template_name = 'accounts/user.html'

    def get_context(self, username, form=None):
        if not form:
            user = models.User.objects.get_or_404(username=username)
            form = forms.UserForm(obj=user)
        data = {'form':form}
        return data

    def get(self, username, form=None):
        data = self.get_context(username, form)
        return render_template(self.template_name, **data)

    def post(self, username):
        form = forms.UserForm(obj=request.form)
        if form.validate():
            user = models.User.objects.get_or_404(username=username)
            if user.email != form.email.data:
                user.is_email_confirmed = False
            user.email = form.email.data
            # user.is_active = form.is_active.data
            # user.is_superuser = form.is_superuser.data
            user.role = form.role.data
            user.save()
            flash('Succeed to update user details', 'success')
            return redirect(url_for('accounts.edit_user', username=username))
        return self.get(username, form)

    def delete(self, username):
        user = models.User.objects.get_or_404(username=username)
        user.delete()

        if request.args.get('ajax'):
            return 'success'

        msg = 'Succeed to delete user'

        flash(msg, 'success')
        return redirect(url_for('accounts.users'))

# class SuUsers(MethodView):
#     decorators = [login_required, su_permission.require(401)]
#     template_name = 'accounts/su_users.html'
#     def get(self):
#         users = models.User.objects.all()
#         return render_template(self.template_name, users=users)

# class SuUser(MethodView):
#     decorators = [login_required, admin_permission.require(401)]
#     template_name = 'accounts/user.html'

#     def get_context(self, username, form=None):
#         if not form:
#             user = models.User.objects.get_or_404(username=username)
#             user.weibo = user.social_networks['weibo'].get('url')
#             user.weixin = user.social_networks['weixin'].get('url')
#             user.twitter = user.social_networks['twitter'].get('url')
#             user.github = user.social_networks['github'].get('url')
#             user.facebook = user.social_networks['facebook'].get('url')
#             user.linkedin = user.social_networks['linkedin'].get('url')

#             form = forms.SuUserForm(obj=user)
#         data = {'form':form}
#         return data

#     def get(self, username, form=None):
#         data = self.get_context(username, form)
#         return render_template(self.template_name, **data)

#     def post(self, username):
#         form = forms.SuUserForm(obj=request.form)
#         if form.validate():
#             user = models.User.objects.get_or_404(username=username)

#             user.email = form.email.data
#             user.is_email_confirmed = form.is_email_confirmed.data

#             user.display_name = form.display_name.data
#             user.biography = form.biography.data
#             user.homepage_url = form.homepage_url.data or None
#             user.social_networks['weibo']['url'] = form.weibo.data or None
#             user.social_networks['weixin']['url'] = form.weixin.data or None
#             user.social_networks['twitter']['url'] = form.twitter.data or None
#             user.social_networks['github']['url'] = form.github.data or None
#             user.social_networks['facebook']['url'] = form.facebook.data or None
#             user.social_networks['linkedin']['url'] = form.linkedin.data or None
#             user.save()

#             msg = 'Succeed to update user profile'
#             flash(msg, 'success')

#             return redirect(url_for('accounts.su_edit_user', username=user.username))

#         return self.get(form)

# class Profile(MethodView):
#     decorators = [login_required]
#     template_name = 'accounts/settings.html'

#     def get(self, form=None):
#         if not form:
#             # user = get_current_user()
#             user = current_user
#             user.weibo = user.social_networks['weibo'].get('url')
#             user.weixin = user.social_networks['weixin'].get('url')
#             user.twitter = user.social_networks['twitter'].get('url')
#             user.github = user.social_networks['github'].get('url')
#             user.facebook = user.social_networks['facebook'].get('url')
#             user.linkedin = user.social_networks['linkedin'].get('url')
#             form = forms.ProfileForm(obj=user)
#         data = {'form': form}
#         return render_template(self.template_name, **data)

#     def post(self):
#         form = forms.ProfileForm(obj=request.form)
#         if form.validate():
#             # user = get_current_user()
#             user = current_user
#             if user.email != form.email.data:
#                 user.email = form.email.data
#                 user.is_email_confirmed = False

#             user.display_name = form.display_name.data
#             user.biography = form.biography.data
#             user.homepage_url = form.homepage_url.data or None
#             user.social_networks['weibo']['url'] = form.weibo.data or None
#             user.social_networks['weixin']['url'] = form.weixin.data or None
#             user.social_networks['twitter']['url'] = form.twitter.data or None
#             user.social_networks['github']['url'] = form.github.data or None
#             user.social_networks['facebook']['url'] = form.facebook.data or None
#             user.social_networks['linkedin']['url'] = form.linkedin.data or None
#             user.save()

#             msg = 'Succeed to update user profile'
#             flash(msg, 'success')

#             return redirect(url_for('blog_admin.index'))

#         return self.get(form)

class Password(MethodView):
    decorators = [login_required]
    template_name = 'accounts/password.html'

    def get(self, form=None):
        if not form:
            form = forms.PasswordForm()
        data = {'form': form}
        return render_template(self.template_name, **data)

    def post(self):
        form = forms.PasswordForm(obj=request.form)
        if form.validate():
            # if not current_user.verify_password(form.current_password.data):
            #     return 'current password error', 403 
            current_user.password = form.new_password.data
            current_user.save()
            # return 'waiting to code'
            msg = 'Succeed to update password'
            flash(msg, 'success')

            return redirect(url_for('accounts.password'))

        return self.get(form)


accounts.add_url_rule('/login/', 'login', login, methods=['GET', 'POST'])
accounts.add_url_rule('/logout/', 'logout', logout)
accounts.add_url_rule('/registration/', 'register', register, methods=['GET', 'POST'])

app/templates/_form.html
{% macro render(form) -%}

{% for field in form %}
  {% if field.type in ['CSRFTokenField', 'HiddenField'] %}
    {{ field() }}
  {% elif field.type == "BooleanField" %}
  <div class="checkbox">
  <label>
    {{ field() }} {{ field.label }}
  </label>

  </div>
  {% else %}
    <div class="clearfix {% if field.errors %}has-error{% endif %} form-group">
      {{ field.label }}
        {{ field(class_="form-control") }}
        {% if field.errors or field.help_text %}
          <span class="help-block">
          {% if field.errors %}
            {{ field.errors|join(' ') }}
          {% else %}
            {{ field.help_text }}
          {% endif %}
          </span>
        {% endif %}
    </div>
  {% endif %}
{% endfor %}

{% endmacro %}

app/templates/_msg.html
{% macro render_msg() %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flash_msg">
    {% for category, message in messages %}
      {% if category == 'message' %}
        {% set category='info' %}
      {% endif %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert" style="margin-bottom: 0px">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}

{% endmacro %}

app/templates/_pagination.html
{% macro render_pagination(pagination, url_params=None) %}
  <nav>
    <ul class="pagination">
      {% if not pagination.has_prev %}
        <li class="disabled">
          <a href="?page=1{%if url_params %}&{{ url_params }}{% endif %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
        <a href="?page={{ pagination.pre_num }}{%if url_params %}&{{ url_params }}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
      {% endif %}
    
      {%- for page in pagination.iter_pages() %}
        {% if page %}
          {% if page != pagination.page %}
            <li><a href="?page={{ page }}{%if url_params %}&{{ url_params }}{% endif %}">{{ page }}</a></li>
          {% else %}
            <li class="disabled"><a href="?page={{ page }}{%if url_params %}&{{ url_params }}{% endif %}"><strong>{{ page }}</strong></a></li>
          {% endif %}
        {% else %}
          <!-- <span class=ellipsis>…</span> -->
          <li class="disabled"><a href="#">...</a></li>
        {% endif %}
      {%- endfor %}
      {% if not pagination.has_next %}
        <li class="disabled">
          <span aria-hidden="true">&raquo;</span>
        </li>
      {% else %}
        <li>
          <a href="?page={{ pagination.next_num }}{%if url_params %}&{{ url_params }}{% endif %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}      
    </ul>
  </nav>
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>{% block title %}JuneMessage{% endblock %}</title>
    
    
    <!-- Bootstrap Core CSS -->
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">

    
    <!-- Custom CSS -->
    
    {% block css %}{% endblock %}
    <!-- Custom Fonts -->
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
{% import "_msg.html" as messages %}
{{ messages.render_msg() }}
    <!-- Navigation -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">JuneMessage</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="_active"><a href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a></li>
            
            {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Applications <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('oauth.applications') }}">All Applications</a></li>
                <li><a href="{{ url_for('oauth.new_application') }}">New Application</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('accounts.users') }}">All Users</a></li>
                <li><a href="{{ url_for('accounts.add_user') }}">New User</a></li>
              </ul>
            </li>
            {% endif %}
          </ul>
          
            

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ current_user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('accounts.logout') }}">Logout</a></li>
                <!-- <li class="divider"></li>
                <li><a href="#">Category</a></li> -->
              </ul>
            </li>
          {% else %}
            <li><a href="{{ url_for('accounts.login') }}">Login</a></li>
            <li><a href="{{ url_for('accounts.register') }}">Register</a></li>
          {% endif %}
          </ul>
        </div>
      </div><!-- /.container-fluid -->
    </nav>


    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}
    <div class="container">
        <!-- Main Content -->
        
        {%block main %}{% endblock %}
    </div>
    <hr>
    
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <!-- <ul class="list-inline text-center">
                        <li>
                            <a href="https://creativecommons.org/licenses/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-creative-commons fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/flyhigher139/OctBlog" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul> -->
                    <p class="copyright text-muted text-center">Copyright &copy; JuneMessage 2016</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery -->
    <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/bootbox.js/4.4.0/bootbox.min.js"></script>
    
    <!-- Custom Theme JavaScript -->
    {% block js %}
    {% endblock %}
    
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{%block main %}
<p>Wellcome to JuneMessage</p>
{% endblock %}